version: "3"
services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus3
    restart: always
    ports:
      - 8081:8081
    volumes:
      - /data/devops-compose/nexus/nexus-data:/nexus-data
