version: "3"
services:
  sonar:
    image: sonarqube:lts-community
    depends_on:
      - db
    restart: always
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - /data/devops-compose/sonarqube/data:/opt/sonarqube/data
      - /data/devops-compose/sonarqube/logs:/opt/sonarqube/logs
      - /data/devops-compose/sonarqube/extensions:/opt/sonarqube/extensions
      - /etc/localtime:/etc/localtime:ro
    networks:
      - sonar-network

  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - /data/devops-compose/sonarqube/postgresql:/var/lib/postgresql
      - /data/devops-compose/sonarqube/postgresql/data:/var/lib/postgresql/data
    networks:
      - sonar-network

networks:
  sonar-network:

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:
