version: '3'
services:
  gerrit:
    image: gerritcodereview/gerrit
    ports:
      - "29418:29418"
      - "8088:8080"
    links:
      - postgres
    depends_on:
      - postgres
    volumes:
      - /data/devops-compose/gerrit/etc:/var/gerrit/etc
      - /data/devops-compose/gerrit/git:/var/gerrit/git
      - /data/devops-compose/gerrit/index:/var/gerrit/index
      - /data/devops-compose/gerrit/cache:/var/gerrit/cache
    environment:
      - CANONICAL_WEB_URL=http://47.103.158.239:8088/
#    entrypoint: java -jar /var/gerrit/bin/gerrit.war init -d /var/gerrit

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=reviewdb
    volumes:
      - /data/devops-compose/gerrit/postgres:/var/lib/postgresql/data
